import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import '@smastrom/react-rating/style.css'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RomaFood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
          <link rel="icon" href="/romalogo.png" type="image/png" />
          <body className={inter.className}>
            <Provider>{children}</Provider>
          </body>
        </html>
    </ClerkProvider>

  );
}
